"""
Auditing, tested against the spike fixture.

The fixture is not a file invented for the tests: it is the same `.docx` that
was generated by hand, opened in Word with Zotero, refreshed and switched from
Vancouver to APA (SPEC §12.2 and §12.3). We know what Word makes of it.

So the assertions below do not check that the code agrees with itself — they
check that it reproduces, offline, a behaviour that was observed.

    uv run --with pytest python -m pytest tests -q
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

from catena.audit import ERROR, audit, render
from catena.fields import parse_citations, parse_prefs
from catena.ooxml import Document, xml_text

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "spike" / "catena-spike.docx"


@pytest.fixture(scope="module")
def doc() -> Document:
    return Document.open(FIXTURE)


# --- the OOXML parser --------------------------------------------------------


def test_w_t_does_not_swallow_lookalike_tags():
    """SPEC §14.3, trap 8: `<w:t[^>]*>` also matches `<w:tcPr>`."""
    frag = "<w:tcPr><w:vAlign w:val='top'/></w:tcPr><w:t>real text</w:t><w:tab/>"
    assert xml_text(frag) == "real text"


def test_xml_entities_are_resolved():
    assert xml_text("<w:t>Bullo &amp; Hearn</w:t>") == "Bullo & Hearn"


# --- the shape of the fixture ------------------------------------------------


def test_the_fixture_has_its_five_cases(doc: Document):
    assert len(parse_citations(doc)) == 5
    assert doc.counts()["bibliography_fields"] == 1


def test_citation_ids_are_unique_per_occurrence(doc: Document):
    """SPEC §7.1: unique per occurrence, not per item."""
    ids = [c.citation_id for c in parse_citations(doc)]
    assert len(set(ids)) == len(ids) == 5


def test_case_2_carries_no_id_field(doc: Document):
    """SPEC §7.7: with `uris` present the id is never read, and Word agrees."""
    assert parse_citations(doc)[1].items[0].raw_id is None


def test_case_4_is_a_grouped_citation(doc: Document):
    """SPEC §11.2 item 12: the (1,2) form, one field with two citationItems."""
    assert len(parse_citations(doc)[3].items) == 2


def test_uris_are_always_present(doc: Document):
    """SPEC §7.7: the fallback branch iterates `uris`, so it cannot be missing."""
    for c in parse_citations(doc):
        for item in c.items:
            assert item.uris, f"citation #{c.order + 1} has no uris"


def test_prefs_are_reassembled(doc: Document):
    prefs = parse_prefs(doc)
    assert prefs is not None
    assert prefs.style_name == "vancouver"
    assert prefs.field_type == "Field"
    assert prefs.chunks == 2, "the 255-character split must produce two chunks"


# --- the checks --------------------------------------------------------------


def test_audit_finds_the_duplicate_surrogate():
    """The defect observed in Word (SPEC §12.2 case 5), found again offline."""
    report = audit(FIXTURE)
    assert "duplicate-surrogate" in [f.code for f in report.by_level(ERROR)]
    assert not report.clean


def test_audit_finds_the_malformed_doi():
    assert any(f.code == "malformed-doi" for f in audit(FIXTURE).findings)


def test_render_does_not_blow_up():
    assert FIXTURE.name in render(audit(FIXTURE))


# --- the CLI -----------------------------------------------------------------


def test_cli_exits_1_when_there_are_errors():
    r = subprocess.run(
        [sys.executable, "-m", "catena.cli", "audit", str(FIXTURE)],
        capture_output=True,
        text=True,
        cwd=ROOT,
        env={**os.environ, "PYTHONPATH": "src"},
    )
    assert r.returncode == 1
    assert "duplicate-surrogate" in r.stdout


def test_a_file_that_is_not_a_docx_is_reported(tmp_path: Path):
    fake = tmp_path / "fake.docx"
    fake.write_bytes(b"not a zip")
    with pytest.raises(Exception):
        audit(fake)
